name: apple-fspm
channels:
  - fredboudon
  - conda-forge
  - defaults
dependencies:
  - alinea.caribu=8.0.7
  - ann=1.1.3
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - boost=1.72.0
  - boost-cpp=1.72.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cgal-cpp=5.2
  - colorama=0.4.6
  - cycler=0.11.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - eigen=3.4.0
  - entrypoints=0.4
  - ephem=4.1.3
  - fonttools=4.38.0
  - freetype=2.12.1
  - geographiclib=1.52
  - geopy=2.3.0
  - icu=69.1
  - importlib-metadata=4.11.4
  - importlib_resources=5.10.2
  - intel-openmp=2023.0.0
  - ipykernel=6.16.2
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.8
  - jupyter_core=4.11.1
  - kiwisolver=1.4.4
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.14
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.39
  - libqglviewer=2.8.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2022.1.0
  - mpfr=4.1.0
  - mpir=3.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - numpy=1.20.3
  - openalea.lpy=3.9.2
  - openalea.mtg=2.0.5
  - openalea.plantgl=3.14.1
  - openjpeg=2.5.0
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.3.5
  - parso=0.8.3
  - path=16.5.0
  - path.py=12.5.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - prompt-toolkit=3.0.36
  - psutil=5.9.3
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pygments=2.14.0
  - pyopengl=3.1.6
  - pyparsing=3.0.9
  - pyqglviewer=1.1.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.7
  - pywin32=303
  - pyzmq=24.0.1
  - qhull=2020.2
  - qt=5.12.9
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - setuptools=59.8.0
  - six=1.16.0
  - sqlite=3.40.0
  - tbb=2021.7.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.8.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - ucrt=10.0.22621.0
  - unicodedata2=14.0.0
  - vc=14.3
  - vs2015_runtime=14.32.31332
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xlrd=2.0.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - alinea-caribu==8.0.7
      - openalea-lpy==3.9.2
      - openalea-mtg==2.0.5
      - openalea-plantgl==3.14.1
